spring:

  # ActiveMQ Settings
  activemq:
      broker-url: tcp://localhost:${port}

  # JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000

# Logging Settings
logging:
  pattern:
    console: "%msg%n"
  level:
      - ".=info"
      - "ru.nikitamugen=debug"
      - "org.springframework=info"